### PR TITLE
Fix typo in PARALLELISM.md

### PR DESCRIPTION
**Pull request by Nicoretti**
Hi @littleK0i,

while reading the docs, I think I stumbled upon a small typo.

best
Nico

### CODE REVIEW

**Comment by littleK0i** [comment]
@Nicoretti , well the thing is, I cannot merge it myself.

GitHub says: "You’re not to merge this pull request."

**Review by littleK0i — APPROVED** [review]

**Comment by tkilias** [comment]
The issue is, that our automated branch protection configuration requires that all checks for a PR run. However, the gh actions are limited here to changes on python files. I tried to trigger them manually not sure if it recognizes this.

**Comment by Nicoretti** [comment]
@littleK0i thanks for the feedback and sorry for the delay. @tkilias good point. 
What do the both of you think would be a solution for this in the long run?
* Add `- **.md` to the trigger paths?
  (I could include it within this change, or create a separate PR)

**Comment by tkilias** [comment]
> @littleK0i thanks for the feedback and sorry for the delay. @tkilias good point. 
> What do the both of you think would be a solution for this in the long run?
> * Add `- **.md` to the trigger paths?
>   (I could include it within this change, or create a separate PR)

I think, I would remove the file filter

**Review by littleK0i — APPROVED** [review]

**Comment by tkilias** [comment]
The tests seem to fail, because we get an SSL error for Python 3.9. I am not sure, if this is a general issue, or if it only happens because we poll the DB during startup. Or, if it is a problem with Exasol 7.0+. @Nicoretti could you test this locally?

https://github.com/exasol/pyexasol/blob/c9b1f445d1f1424b8cf9aaa7b42945c935fdbb0e/examples/_wait_container.py#L39

**Comment by allipatev** [comment]
@tkilias @Nicoretti 
Meanwhile, PR checks look still broken :) 
https://github.com/exasol/pyexasol/runs/7647714470?check_suite_focus=true
```
...
BucketFS: File '/exaudf/exaudfclient' does not exist. (Session: 1740127461795233792)
...
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2633)
...
```
Do you know what could be done to merge my https://github.com/exasol/pyexasol/pull/92?

**Comment by redcatbear** [comment]
@littleK0i , I gave you `maintain` permissions on the project. Please check if you can merge now.

**Comment by littleK0i** [comment]
@redcatbear , yes, now I can merge. Thank you!

**Comment by redcatbear** [comment]
@littleK0i , don't mention it. I should have realized a lot sooner that `write` was insufficient.

**Pull request merged**
